apiVersion: v1
kind: Service
metadata:
  name: demo-postgres
  namespace: default
  labels:
    app: demo-postgres
    demo.dependency-controller/scenario: postgres-app
spec:
  selector:
    app: demo-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
