apiVersion: core.example.com/v1
kind: Dependency
metadata:
  labels:
    app.kubernetes.io/name: dependency
    app.kubernetes.io/managed-by: kustomize
  name: dependency-sample
spec:
  # TODO(user): Add fields here
