apiVersion: core.example.com/v1
kind: Dependency
metadata:
  labels:
    app.kubernetes.io/name: dependency
    app.kubernetes.io/managed-by: kustomize
  name: dependency-sample
  namespace: default
spec:
  condition: serviceHealthy
  dependency:
    apiVersion: apps/v1
    kind: Deployment
    name: pod1-deployment
  dependent:
    apiVersion: apps/v1
    kind: Deployment
    name: pod2-deployment
  # desiredReplicas: 2
